export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAILURE = 'USER_DETAILS_FAILURE';




export const USER_LISTING_REQUEST = 'USER_LISTING_REQUEST';
export const USER_LISTING_SUCCESS = 'USER_LISTING_SUCCESS';
export const USER_LISTING_FAILURE = 'USER_LISTING_FAILURE';


export const DYNAMIC_SIDEBAR_REQUEST = 'DYNAMIC_SIDEBAR_REQUEST';
export const DYNAMIC_SIDEBAR_SUCCESS = 'DYNAMIC_SIDEBAR_SUCCESS';
export const DYNAMIC_SIDEBAR_FAILURE = 'DYNAMIC_SIDEBAR_FAILURE';